# baseURL = "http://example.org/"
# languageCode = "en-us"
# title = "My New Hugo Site"

baseurl = "https://vxe.github.io/resume/"
languageCode = "en-us"
title = "Docs"
# Enable comments by entering your Disqus shortname
disqusShortname = "vxe"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-hikari-theme"
publishDir = "docs"
canonifyURLs = true
# pygmentsUseClassic = true
# linenos = inline
PygmentsCodeFences = true
PygmentsStyle = "fruity"




[permalinks]
	post = "/:year/:month/:day/:slug"

[params]
	name = "Vijay Edwin"
	description = "Reference"
	copyright = "POWERED BY [HUGO](//gohugo.io) - THEME: [HIKARI](//github.com/digitalcraftsman/hugo-hikari-theme) - © Vijay Edwin"

	# Custom assets can be linked with their paths relative to static/
	custom_css = []
	custom_js  = []

	# Links to newer/older blog posts
	newer = "Newer"
	older = "Older"

	pageNotFoundTitle = "Page not found"
	pageNotFoundSubtitle = "Sorry, but the requested page wasn’t <br> found on the server."

[params.offcanvas]
	# Menu items
	title = "Hi, I'm Vijay Edwin"
	bio = "Just another guy"
	subscribe = "Subscribe"
	followme = "Follow me on"

	# Enable Google search
	search_enabled = false
	search = "Search"

	[[params.offcanvas.socialnetworks]]
		name = "Github"
		url = "//github.com/vxe"

	[[params.offcanvas.socialnetworks]]
		name = "Twitter"
		url = "//twitter.com/vedwinnnnnn"
